knp_paginator:
  template:
    pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/twitter_bootstrap_v4_material_design_icons_sortable_link.html.twig'
    filtration: '@KnpPaginator/Pagination/filtration.html.twig'